"""empty message

Revision ID: 2e36249966fe
Revises: 1406d00d507a
Create Date: 2023-08-25 22:33:41.867570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e36249966fe'
down_revision = '1406d00d507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('favorite_people_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('favorite_people_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
