"""empty message

Revision ID: 3c7af3619097
Revises: 9b5f8237284a
Create Date: 2023-08-25 23:23:55.510325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7af3619097'
down_revision = '9b5f8237284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorites', type_='unique')
        batch_op.create_unique_constraint('unique_favorites', ['user_id', 'people_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_favorites', type_='unique')
        batch_op.create_unique_constraint('unique_favorites', ['user_id'])

    # ### end Alembic commands ###
