"""empty message

Revision ID: c14956dabfa1
Revises: 2e36249966fe
Create Date: 2023-08-25 22:55:15.636123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14956dabfa1'
down_revision = '2e36249966fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('unique_favorites', type_='unique')
        batch_op.create_unique_constraint('unique_favorites', ['user_id'])
        batch_op.drop_constraint('favorites_favorite_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_favorite_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])
        batch_op.drop_column('favorite_people_id')
        batch_op.drop_column('url_address')
        batch_op.drop_column('name')
        batch_op.drop_column('favorite_planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url_address', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('favorite_people_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_favorite_people_id_fkey', 'people', ['favorite_people_id'], ['id'])
        batch_op.create_foreign_key('favorites_favorite_planet_id_fkey', 'planets', ['favorite_planet_id'], ['id'])
        batch_op.drop_constraint('unique_favorites', type_='unique')
        batch_op.create_unique_constraint('unique_favorites', ['user_id', 'url_address'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###
